### ISSUE TITLE
Java convertcoordinate Issue

### ISSUE THREAD

**Issue by gk7279** [rpiskol/SNPiR#2]
Hi Robert-

When I merge the mouse and splicing junction files, samtools was complaining of duplicate names. So I appended the occurence number to the end of chromosome name. Now while trying to convert coordinates, I am getting this error

*java.lang.NumberFormatException: For input string: "10027147_12"*

The delimiter before appending the occurence is "_". Should I use a dash instead?

Please let me know. Thanks.

**Comment by ahdee** [comment]
Not Robert, but how many junction files are you merging.  I think, guess, is that you just need to merge one junction file with the index.  The junction file you concatenate is based on your read length? Just my guess - let me know if you resolve it with multiples though.
